Jeff "is this really texting? or is this a fake?"
comuter EXTERMINATING...
computer SHUTTING DOWN YOUR COMPUTER...
computer DELETING ALL FILES...
computer DELETING ACCOUNT...
computer DELETING SECURITY...
computer DOWNLOADING VIRUSES...
cori tapping keys 'type type type!' cori "ok, I entered the kill code :)"

KILLLL CCOOOODDDEE ENNTTTERRRREEEDDD SSHUTTTINNNGG DOOOWWWWNNNNNN.!.!.!.!...
